<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuite1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>1ddcaa27-dbbd-4100-a331-70370cacbce9</testSuiteGuid>
   <testCaseLink>
      <guid>e15f2815-9b90-4baf-9073-18f6e6a5d72f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>facc1c07-b0fa-48b4-9fe5-f907f2e48801</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data1</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>facc1c07-b0fa-48b4-9fe5-f907f2e48801</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>67beb52f-adda-453f-8361-1b10f0091c40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>facc1c07-b0fa-48b4-9fe5-f907f2e48801</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>763b4b24-0eb0-4797-b558-3bccf0d507a6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d755a9d-e5bb-47a4-beb0-e62875b70ead</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase_NewIdea</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>744ffaef-9822-4f3a-be34-bc9de183bc11</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data2</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>744ffaef-9822-4f3a-be34-bc9de183bc11</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Theme</value>
         <variableId>9a238142-dc78-4811-a8e5-bc6c5180f6f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>744ffaef-9822-4f3a-be34-bc9de183bc11</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FunctionType</value>
         <variableId>38bdd683-e9d7-471a-a959-548425e0f1fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>744ffaef-9822-4f3a-be34-bc9de183bc11</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Processname</value>
         <variableId>715afd2b-f309-408d-b937-afda65b3d0db</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
